CREATE DATABASE food_delivery;
USE food_delivery;

select * from food_ordering_behaviour limit 10;

-- Total revenue 
SELECT 
    ROUND(SUM(order_value), 2) AS Total_Revenue
FROM
    food_ordering_behaviour;

-- Revenue generated by cities 
SELECT 
    city, ROUND(SUM(order_value), 2) AS Total_Revenue
FROM
    food_ordering_behaviour
GROUP BY city order by Total_Revenue desc;

-- which cuisine is more  profitable ?
SELECT 
    cuisine, ROUND(SUM(order_value), 2) AS Total_Revenue
FROM
    food_ordering_behaviour
GROUP BY cuisine
ORDER BY Total_Revenue DESC;

-- which restaurant type gives more revenue ?
SELECT 
    restaurant_type, ROUND(SUM(order_value), 2) AS Total_Revenue
FROM
    food_ordering_behaviour
GROUP BY restaurant_type
ORDER BY Total_Revenue DESC;

-- Weekend vs Weekday → which day have more revenue at which time  ?

SELECT 
        day_type,
        order_time,
        SUM(order_value) AS total_revenue
    FROM food_ordering_behaviour
    GROUP BY day_type, order_time order by day_type desc ;

-- repeat customer vs new customer , avg orders , 
SELECT 
    CASE
        WHEN LOWER(is_repeat_order) = 'yes' THEN 'Repeat Customer'
        ELSE 'New Customer'
    END AS customer_type,
    COUNT(DISTINCT user_id) AS total_users,
    COUNT(order_id) AS total_orders,
    SUM(order_value) AS total_revenue,
    ROUND(AVG(order_value),2) AS avg_order_value
FROM food_ordering_behaviour
GROUP BY customer_type;

-- most order cuisine  in different cities 

WITH data AS (
    SELECT city, cuisine, COUNT(*) as total_orders
    FROM food_ordering_behaviour
    GROUP BY city, cuisine
)
select * from (SELECT *,
       RANK() OVER (PARTITION BY city ORDER BY total_orders DESC) as rnk
FROM data)t where rnk = 1 ;

-- orders and revenue  in rainy or normal weather

SELECT 
    CASE
        WHEN LOWER(rainy_weather) = 'yes' THEN 'Rainy'
        ELSE 'Normal'
    END AS weather_type,
    COUNT(*) AS total_orders,
    SUM(order_value) AS revenue,
    ROUND(AVG(order_value), 2) AS avg_order,
    CONCAT(
        ROUND(100 * SUM(order_value) / SUM(SUM(order_value)) OVER (), 2),
        '%'
    ) AS revenue_percentage
FROM food_ordering_behaviour
GROUP BY weather_type;

-- Discount Analysis 

SELECT 
    CASE 
        WHEN LOWER(discount_applied) = 'yes' THEN 'Discounted' 
        ELSE 'Non-Discounted' 
    END AS category,
    SUM(order_value) AS revenue,
    COUNT(order_id) AS orders,
    ROUND(AVG(order_value), 2) AS average_order,
    CONCAT(
        ROUND(
            SUM(order_value) * 100.0 / SUM(SUM(order_value)) OVER (), 
            2
        ),
        '%'
    ) AS percentage
FROM food_ordering_behaviour
GROUP BY category;
    
    
-- Rating Analysis

select round(avg(rating_given),2) from  food_ordering_behaviour ;

    SELECT 
        cuisine,
        ROUND(AVG(rating_given),2) AS avg_rating
    FROM food_ordering_behaviour
    GROUP BY cuisine
ORDER BY avg_rating ASC
LIMIT 1;

SELECT 
    CASE
        WHEN time_taken_to_order < 5 THEN 'Fast'
        WHEN time_taken_to_order < 10 THEN 'Medium'
        ELSE 'Slow'
    END AS delivery_speed,
    ROUND(AVG(rating_given),2) AS avg_rating
FROM food_ordering_behaviour
GROUP BY delivery_speed
ORDER BY avg_rating DESC;


-- 7. Time Analysis
-- Peak ordering time kya hai? (order_time)
-- Kaunsa time slot me sabse jyada revenue aata hai?
-- Night vs Morning behavior difference?
select * from food_ordering_behaviour ;
SELECT 
    order_time,
    COUNT(order_id) AS numoforder,
    SUM(order_value) AS revenue,
    round(avg(order_value),2) as avg_price
FROM
    food_ordering_behaviour
GROUP BY order_time
ORDER BY numoforder DESC;

-- Psychological Insights (🔥 very powerful)
-- Mood vs order_value → log happy hote hue zyada spend karte hain?
-- Hunger level vs order_value → high hunger = high spending?
-- Mood vs cuisine → stressed log kya order karte hain?

SELECT 
    mood,
    COUNT(order_id) AS total_orders,
    SUM(order_value) AS revenue,
    ROUND(AVG(order_value),2) AS avg_spending
FROM food_ordering_behaviour
GROUP BY mood
ORDER BY avg_spending DESC;

SELECT 
    hunger_level,
    COUNT(order_id) AS total_orders,
    SUM(order_value) AS revenue,
    ROUND(AVG(order_value),2) AS avg_spending
FROM food_ordering_behaviour
GROUP BY hunger_level
ORDER BY avg_spending DESC;

with data as (SELECT 
    mood,
    cuisine,
    COUNT(*) AS orders
FROM food_ordering_behaviour
GROUP BY mood, cuisine
ORDER BY mood )
select * from 
(select * , rank() over(partition by mood order by orders desc ) as rnk from data )t where rnk = 1;

-- 9. Delivery Insights
-- Delivery fee ka impact order_value pe hai kya?
-- High delivery time wale orders ki rating low hoti hai kya?

SELECT 
    CASE 
        WHEN delivery_fee <=30 THEN 'low Delivery'
        WHEN delivery_fee <= 50 THEN 'medium Fee'
        ELSE 'High Fee'
    END AS fee_category,
    COUNT(order_id) AS total_orders,
    ROUND(AVG(order_value),2) AS avg_order_value

FROM food_ordering_behaviour
GROUP BY 
    CASE 
        WHEN delivery_fee <=30 THEN 'low Delivery'
        WHEN delivery_fee <= 50 THEN 'medium Fee'
        ELSE 'High Fee'
    END
ORDER BY avg_order_value DESC;


-- Top 5 customers by total spending
-- Top city + cuisine combination
-- Most profitable segment: (city + cuisine + meal_type)
SELECT 
    user_id,
    COUNT(order_id) AS total_orders,
    SUM(order_value) AS total_spending
FROM food_ordering_behaviour
GROUP BY user_id
ORDER BY total_spending DESC
LIMIT 5;

SELECT 
    city,
    cuisine,
    SUM(order_value) AS revenue
FROM food_ordering_behaviour
GROUP BY city, cuisine
ORDER BY revenue DESC
LIMIT 5;

SELECT 
    city,
    cuisine,
    meal_type,
    SUM(order_value) AS revenue,
    COUNT(*) AS orders
FROM food_ordering_behaviour
GROUP BY city, cuisine, meal_type
ORDER BY revenue DESC
LIMIT 10;
